name: sistem_monitoring_kontrol
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.0.5
  mysql1: ^0.20.0
  mqtt_client: ^10.0.0
  logging: ^1.2.0
  fl_chart: ^0.68.0
  gap: ^3.0.1
  carousel_slider: ^4.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  percent_indicator: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    