// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN2H8PbRucu94Hrlx_2ahlB6lEubwr3RA',
    appId: '1:862133095308:web:0be3c9a20e8d381f2de4a9',
    messagingSenderId: '862133095308',
    projectId: 'sistem-monitoring-kontrol',
    authDomain: 'sistem-monitoring-kontrol.firebaseapp.com',
    storageBucket: 'sistem-monitoring-kontrol.firebasestorage.app',
    measurementId: 'G-1JB73YKEZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4LcrGow9SnbGHe1aM8YWvllca2NUAAoY',
    appId: '1:1008179913372:android:5b90f18f38364fdf544359',
    messagingSenderId: '1008179913372',
    projectId: 'hqchulo',
    databaseURL: 'https://hqchulo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hqchulo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv24G-36a_bqPN_Mwe21S3bZRHxJDESFs',
    appId: '1:862133095308:ios:f5999ec4e53c18212de4a9',
    messagingSenderId: '862133095308',
    projectId: 'sistem-monitoring-kontrol',
    storageBucket: 'sistem-monitoring-kontrol.firebasestorage.app',
    iosBundleId: 'com.example.sistemMonitoringKontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv24G-36a_bqPN_Mwe21S3bZRHxJDESFs',
    appId: '1:862133095308:ios:f5999ec4e53c18212de4a9',
    messagingSenderId: '862133095308',
    projectId: 'sistem-monitoring-kontrol',
    storageBucket: 'sistem-monitoring-kontrol.firebasestorage.app',
    iosBundleId: 'com.example.sistemMonitoringKontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN2H8PbRucu94Hrlx_2ahlB6lEubwr3RA',
    appId: '1:862133095308:web:f9d3e2270fdfdaa72de4a9',
    messagingSenderId: '862133095308',
    projectId: 'sistem-monitoring-kontrol',
    authDomain: 'sistem-monitoring-kontrol.firebaseapp.com',
    storageBucket: 'sistem-monitoring-kontrol.firebasestorage.app',
    measurementId: 'G-TC0VN2K702',
  );
}